name: codependence trigger version update 🤼‍♀️

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_ACTION_TOKEN }}
          repository: yowainwright/codependence-post-release
          event-type: codependence_update
